let mockOrders = [
  {
    id: 1,
    orderId: "ORD001",
    customerName: "John Doe",
    orderDate: "2024-03-26",
    status: "Shipped",
  },
  {
    id: 2,
    orderId: "ORD002",
    customerName: "Jane Smith",
    orderDate: "2024-03-25",
    status: "Delivered",
  },
  {
    id: 3,
    orderId: "ORD003",
    customerName: "Michael Johnson",
    orderDate: "2024-03-24",
    status: "Processing",
  },
  {
    id: 4,
    orderId: "ORD004",
    customerName: "Emily Brown",
    orderDate: "2024-03-23",
    status: "Pending",
  },
  {
    id: 5,
    orderId: "ORD005",
    customerName: "David Wilson",
    orderDate: "2024-03-22",
    status: "Cancelled",
  },
  {
    id: 6,
    orderId: "ORD006",
    customerName: "Jessica Thompson",
    orderDate: "2024-03-21",
    status: "Shipped",
  },
  {
    id: 7,
    orderId: "ORD007",
    customerName: "Robert Miller",
    orderDate: "2024-03-20",
    status: "Delivered",
  },
  {
    id: 8,
    orderId: "ORD008",
    customerName: "Emma Garcia",
    orderDate: "2024-03-19",
    status: "Processing",
  },
  {
    id: 9,
    orderId: "ORD009",
    customerName: "Daniel Martinez",
    orderDate: "2024-03-18",
    status: "Pending",
  },
  {
    id: 10,
    orderId: "ORD010",
    customerName: "Olivia Lopez",
    orderDate: "2024-03-17",
    status: "Cancelled",
  },
  {
    id: 11,
    orderId: "ORD011",
    customerName: "William Hernandez",
    orderDate: "2024-03-16",
    status: "Shipped",
  },
  {
    id: 12,
    orderId: "ORD012",
    customerName: "Sophia Gonzalez",
    orderDate: "2024-03-15",
    status: "Delivered",
  },
  {
    id: 13,
    orderId: "ORD013",
    customerName: "James Perez",
    orderDate: "2024-03-14",
    status: "Processing",
  },
  {
    id: 14,
    orderId: "ORD014",
    customerName: "Isabella Sanchez",
    orderDate: "2024-03-13",
    status: "Pending",
  },
  {
    id: 15,
    orderId: "ORD015",
    customerName: "Benjamin Torres",
    orderDate: "2024-03-12",
    status: "Cancelled",
  },
  {
    id: 16,
    orderId: "ORD016",
    customerName: "Mia Ramirez",
    orderDate: "2024-03-11",
    status: "Shipped",
  },
  {
    id: 17,
    orderId: "ORD017",
    customerName: "Logan Flores",
    orderDate: "2024-03-10",
    status: "Delivered",
  },
  {
    id: 18,
    orderId: "ORD018",
    customerName: "Alexander Cruz",
    orderDate: "2024-03-09",
    status: "Processing",
  },
  {
    id: 19,
    orderId: "ORD019",
    customerName: "Charlotte Ortega",
    orderDate: "2024-03-08",
    status: "Pending",
  },
];

export default mockOrders;
