let mockProducts = [
  {
    id: 1,
    name: "Product A",
    category: "Electronics",
    price: 599.99,
    stockQuantity: 100,
  },
  {
    id: 2,
    name: "Product B",
    category: "Clothing",
    price: 39.99,
    stockQuantity: 50,
  },
  {
    id: 3,
    name: "Product C",
    category: "Home & Kitchen",
    price: 149.5,
    stockQuantity: 75,
  },
  {
    id: 4,
    name: "Product D",
    category: "Electronics",
    price: 799.0,
    stockQuantity: 30,
  },
  {
    id: 5,
    name: "Product E",
    category: "Sports",
    price: 129.99,
    stockQuantity: 80,
  },
  {
    id: 6,
    name: "Product F",
    category: "Beauty",
    price: 19.99,
    stockQuantity: 120,
  },
  {
    id: 7,
    name: "Product G",
    category: "Furniture",
    price: 249.0,
    stockQuantity: 60,
  },
  {
    id: 8,
    name: "Product H",
    category: "Books",
    price: 29.95,
    stockQuantity: 150,
  },
  {
    id: 9,
    name: "Product I",
    category: "Clothing",
    price: 49.99,
    stockQuantity: 100,
  },
  {
    id: 10,
    name: "Product J",
    category: "Electronics",
    price: 899.99,
    stockQuantity: 25,
  },
  {
    id: 11,
    name: "Product K",
    category: "Home & Kitchen",
    price: 199.99,
    stockQuantity: 90,
  },
  {
    id: 12,
    name: "Product L",
    category: "Toys & Games",
    price: 79.95,
    stockQuantity: 70,
  },
  {
    id: 13,
    name: "Product M",
    category: "Sports",
    price: 79.99,
    stockQuantity: 110,
  },
  {
    id: 14,
    name: "Product N",
    category: "Beauty",
    price: 9.99,
    stockQuantity: 200,
  },
  {
    id: 15,
    name: "Product O",
    category: "Tools & Home Improvement",
    price: 149.99,
    stockQuantity: 40,
  },
  {
    id: 16,
    name: "Product P",
    category: "Books",
    price: 14.5,
    stockQuantity: 180,
  },
  {
    id: 17,
    name: "Product Q",
    category: "Clothing",
    price: 29.99,
    stockQuantity: 80,
  },
  {
    id: 18,
    name: "Product R",
    category: "Electronics",
    price: 699.0,
    stockQuantity: 35,
  },
  {
    id: 19,
    name: "Product S",
    category: "Furniture",
    price: 299.5,
    stockQuantity: 55,
  },
  {
    id: 20,
    name: "Product T",
    category: "Home & Kitchen",
    price: 99.0,
    stockQuantity: 85,
  },
];

export default mockProducts;
